# Generated by Django 4.1.3 on 2022-11-25 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="interest",
            field=models.ManyToManyField(
                related_name="post_like", to="TinDevApp.candidate"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="not_interest",
            field=models.ManyToManyField(
                related_name="post_dislike", to="TinDevApp.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="expiration_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
