# Generated by Django 4.1.3 on 2022-11-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0002_post_interest_post_not_interest_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="interest",),
        migrations.RemoveField(model_name="post", name="not_interest",),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.CharField(max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_candidate",
                        to="TinDevApp.candidate",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest",
                        to="TinDevApp.post",
                    ),
                ),
            ],
        ),
    ]
