# Generated by Django 4.1.3 on 2022-11-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0003_remove_post_interest_remove_post_not_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest",
                to="TinDevApp.candidate",
            ),
        ),
    ]
