# Generated by Django 4.1.3 on 2022-11-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0005_rename_created_by_interest_candidate"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="job_company",),
        migrations.RemoveField(model_name="application", name="job_title",),
        migrations.AddField(
            model_name="application",
            name="candidate_skill",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="application",
            name="candidate_year",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="TinDevApp.post",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="candidate_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="application",
            name="candidate_username",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.DeleteModel(name="Interest",),
    ]
