# Generated by Django 3.2.13 on 2022-11-30 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TinDevApp', '0011_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_expire',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APLY', 'Applied/Pending'), ('REJT', 'Rejected'), ('ACCT', 'Accepted'), ('EXND', 'Offer Extended'), ('EXPR', 'Expired')], default='APLY', max_length=4),
        ),
    ]
