# Generated by Django 3.2.13 on 2022-11-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TinDevApp', '0012_auto_20221130_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='offer_expire',
        ),
    ]
