# Generated by Django 3.2.13 on 2022-11-30 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TinDevApp', '0013_remove_application_offer_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_expire',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
