# Generated by Django 3.2.13 on 2022-11-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_num', models.IntegerField()),
                ('candidate_name', models.CharField(max_length=30)),
                ('candidate_username', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('job_company', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('APLY', 'Applied/Pending'), ('REJT', 'Rejected'), ('ACCT', 'Accepted'), ('EXND', 'Offer Extended')], default='APLY', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('years', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_username', models.CharField(default='', max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('expiration_date', models.DateField()),
                ('applicant_count', models.IntegerField(default=0)),
                ('pos_type', models.CharField(choices=[('FULL', 'Full-Time'), ('PART', 'Part-Time')], default='FULL', max_length=4)),
                ('active', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='FULL', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
