# Generated by Django 4.1.3 on 2022-11-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0004_alter_interest_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interest", old_name="created_by", new_name="candidate",
        ),
    ]
