# Generated by Django 4.1.3 on 2022-11-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0007_post_hide_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="hide_post",),
    ]
