# Generated by Django 4.1.3 on 2022-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0008_remove_post_hide_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_num", models.IntegerField()),
                ("candidate_username", models.CharField(default="", max_length=30)),
            ],
        ),
    ]
