# Generated by Django 4.1.3 on 2022-11-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TinDevApp", "0009_notinterest"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="candidate_name",),
        migrations.RemoveField(model_name="application", name="candidate_skill",),
        migrations.RemoveField(model_name="application", name="candidate_year",),
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="TinDevApp.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="TinDevApp.post",
            ),
        ),
    ]
