# Generated by Django 3.2.13 on 2022-11-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TinDevApp', '0010_remove_application_candidate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_salary', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('app_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='TinDevApp.application')),
            ],
        ),
    ]
